### PR TITLE
Use bunny publish instead of sneakers

### PR DESCRIPTION
**Pull request by phyrog**
Same as in the backend.

### CODE REVIEW

**Comment by phyrog** [comment]
Ugh. Who needs tests anyway

**Comment by eugenk** [comment]
Almost there. The Coverage decreased.

**Comment by phyrog** [comment]
I think that's just a display bug. Locally it says 100% for me

**Comment by eugenk** [comment]
Right. For me, too. I should focus more on local tests when codecov is red.

**Comment by phyrog** [comment]
I think it got confused because I amended the last commit a few seconds after pushing.

**Pull request merged**
